
s/~env~/DEV/g
s/~domain~/apps.mg-z.ibmlab.de/g
s/~SOURCE_DOMAIN1_NAME~/INTERNAL/g
s/~source_qmgr_hostname1~/ibmdemo01/g
s/~source_domain1~/svc/g
s/~source_qmgr_port1~/1414/g
s/~SOURCE_DOMAIN2_NAME~/MG/g
s/~source_qmgr_hostname2~/ibmdemo01/g
s/~~source_domain2~~/apps.mg-z.ibmlab.de/g
s/~source_qmgr_port2~/443/g
s/~SOURCE_DOMAIN3_NAME~/MM/g
s/~source_qmgr_hostname3~/ibmdemo01/g
s/~~source_domain3~~/apps.mm-z.ibmlab.de/g
s/~source_qmgr_port3~/443/g
s/~TARGET_DOMAIN1_NAME~/INTERNAL/g
s/~target_qmgr_hostname1~/ibmdemo01/g
s/~target_domain1~/svc/g
s/~target_qmgr_port1~/1414/g
s/~TARGET_DOMAIN2_NAME~/INTERNAL/g
s/~target_qmgr_hostname2~/ibmdemo01/g
s/~target_domain2~/apps.mg-z.ibmlab.de/g
s/~target_qmgr_port2~/443/g
s/~TARGET_DOMAIN3_NAME~/INTERNAL/g
s/~target_qmgr_hostname3~/ibmdemo01/g
s/~target_domain3~/apps.mm-z.ibmlab.de/g
s/~target_qmgr_port3~/443/g